name = Homepage
description = ENUF Homepage layout.
preview = preview.png
template = homepage-layout

; Regions
regions[branding]       = Branding
regions[navigation]     = Navigation bar
regions[header]         = Header
regions[hero]           = Hero
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/homepage/homepage.layout.css
stylesheets[all][] = css/layouts/homepage/homepage.layout.no-query.css
