name = List Page
description = ENUF page layout for lists of content.
preview = preview.png
template = listpage-layout

; Regions
regions[branding]       = Branding
regions[navigation]     = Navigation bar
regions[header]         = Header
regions[hero]           = Hero
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/listpage/listpage.layout.css
stylesheets[all][] = css/layouts/listpage/listpage.layout.no-query.css
